version: '3.9'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MessagingService:ConnectionString=amqp://guest:guest@rabbitmq:5672/
      - Database:ConnectionString=Server=mssql,1433;Database=StudentsManager;User Id=SA;Password=pa$$w0rd;
    ports:
      - "5001:80"
  processor:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MessagingService:ConnectionString=amqp://guest:guest@rabbitmq:5672/
  mssql:
    environment:
      - SA_PASSWORD=pa$$w0rd